import React, { useState } from "react";


// Definindo o tipo de contexto
interface ApiContextType  {
    machines: MachinesTypes[],
    setMachines: (value: MachinesTypes[] | ((prevState: MachinesTypes[]) => MachinesTypes[])) => void
}

export interface MachinesTypes {
    primary_key: string,
    setor: string,
    nome: string,
    so: string,
    usuarios: string[],
    processador: string,
    ram: string,
    motheboard: string,
    armazenamento: string,
    video: string,
    monitores: string[],
    n_maquina: string,
    n_monitores: string[],
    n_nobreak: string,
}

// Criando o contexto com um valor padrão
export const ApiContext = React.createContext<ApiContextType>({} as ApiContextType);


// Adicionando valores para o contexto
export const ApiProvider = ({children}: { children: React.ReactNode }) => {
    const [machines, setMachines] = useState<MachinesTypes[]>([
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },

        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
        {
            primary_key: '15bgh52',
            setor: 'manutenção',
            nome: 'workbenck',
            so: 'Windows10',
            usuarios: [ 'Vitoria', 'Maria'],
            processador: 'Pentium G3260',
            ram: '16 Gb',
            motheboard: 'Gigabyte',
            armazenamento: '500 Gb',
            video: 'RX 580',
            monitores: ['AOC 23.5', 'AOC 23.5'],
            n_maquina: '0128',
            n_monitores: ['0258', '0458'],
            n_nobreak: '0784'
        },
      ]);

    return (
        <ApiContext.Provider value={{ machines, setMachines }}>
            {children}
        </ApiContext.Provider>
    )
}